[Date]


allow_url_fopen = On
allow_url_include= Off
display_errors= Off
file_uploads= On
max_execution_time= 0
max_input_time= -1
max_input_vars= 1000
memory_limit= 128M
post_max_size= 8M
upload_max_filesize= 2M
zlib.output_compression= On
date.timezone=UTC
intl.default_locale= en_US

; Recommended OPcache settings for Symfony
; https://symfony.com/doc/current/performance.html

opcache.enable=0
opcache.enable_cli=0

; The amount of memory to use for OPcache, in megabytes.
opcache.memory_consumption=256

; The maximum number of files to cache.
opcache.max_accelerated_files=20000

; How often to check for changed files, in seconds.
; 1 means always check, which is ideal for development.
; In production, you should set this to 0 and use a cache warmer.
opcache.validate_timestamps=0

; If enabled, OPcache will save comments from PHP source files.
; This is required for some libraries, like Doctrine Annotations.
opcache.save_comments=1

; Preloading configuration
opcache.preload=
opcache.preload_user=nobody

; Realpath cache configuration
realpath_cache_size=4096K
realpath_cache_ttl=600
