# Default server definition
server {
    listen [::]:8080 default_server;
    listen 8080 default_server;
    server_name _;

    sendfile off;
    tcp_nodelay on;
    absolute_redirect off;

    root /var/www/html;
    index index.php index.html;

    # location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to index.php
    #     try_files $uri $uri/ /index.php$is_args$args;
    # }
    location / {
        try_files $uri /index.php?$query_string;
    }


    # Redirect server error pages to the static page /50x.html
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /var/lib/nginx/html;
    }

    # Pass the PHP scripts to PHP-FPM listening on php-fpm.sock
    location ~ '\.php$|^/update.php' {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+?\.php)(|/.*)$;
        fastcgi_pass unix:/run/php-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param QUERY_STRING $query_string;
        fastcgi_intercept_errors on;
        include fastcgi_params;
    }

    location @rewrite {
        rewrite ^/(.*)$ /index.php;
    }

    # Don't allow direct access to PHP files in the vendor directory.
    location ~ /vendor/.*\.php$ {
        deny all;
        return 404;
    }

    # Set the cache-control headers on assets to cache for 5 days
    location ~* \.(jpg|jpeg|gif|png|ico|svg)$ {
        expires max;
        log_not_found off;
    }

    # Passes XML Sitemap over to PHP
    location ~ ^(/[a-z\-]+)?/sitemaps/.*/(xml)/ {
        try_files $uri @rewrite;
        expires max;
    }

    # Passes image style and asset generation to PHP
    location ~ ^(/[a-z\-]+)?/sites/.*/files/(css|js|styles)/ {
        try_files $uri @rewrite;
        expires max;
    }

    # Handle private files through Drupal. Private file's path can come
    # with a language prefix.
    location ~ ^(/[a-z\-]+)?/system/files/ {
        try_files $uri /index.php?$query_string;
    }

    # Deny access to . files, for security
    location ~ /\. {
        log_not_found off;
        deny all;
    }

    # Allow fpm ping and status from localhost
    location ~ ^/(fpm-status|fpm-ping)$ {
        access_log /dev/stdout;
        error_log /dev/stdout info;
        allow 127.0.0.1;
        deny all;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_pass unix:/run/php-fpm.sock;
    }

    # Extra Omeka-S rules for the default server

    # Robots and favicon
    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    # Block suspicious paths like /foo/../bar.php
    location ~ \..*/.*\.php$ {
        return 403;
    }

    location /admin {
        try_files $uri /index.php?$args;
    }

    # PHP to FPM
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_intercept_errors on;
        fastcgi_pass unix:/run/php-fpm.sock;
    }


}
